<div id="sidebar">
    <h2>Site Map</h2>
    <ul>
      <li><a href="default.asp">Home</a></li>
      
      <li><a href="IDP_download_current.asp">Downloads</a></li>
      <li><a href="IDP_contact.asp">Contact</a></li>
      <li><a href="IDP_requirements.asp">Requirements</a></li>
      <li><a href="IDP_faq.asp">FAQ</a></li>
  
    </ul>
    <h3>Help</h3>
    <ul>
      
     

      <li><a href="IDP_manual.asp">Manual</a></li>
      <li><a href="IDP_tutorial.asp">Tutorial</a></li>
      
    </ul>
    <h2>Download</h2>
    <h3>Current release</h3>
    <ul>
      <li><a href="IDP_download_current.asp"><img src="images/download.png"> IDP 0.1.9</a> (<a href="IDP_download_current.asp#notes">notes</a>)</li>
    </ul>

    <!-- #include file="usefullinks.inc" -->

    <br><ul><center><img src="images/seal.gif" width="75%" hight="75%"><center></ul>
  </div>


