  <div id="page_title_area">
    <!-- STANDARD PAGE TITLE; NO DECORATIVE GRAPHIC -->
    <!-- <div id="page_title_leftcontent"> -->
    <div id="page_title_leftcontent">
      <h1>IDP-denovo</h1>
      <ul>
        <li>IDP-denovo is a tool for <b><i>de novo</i></b> transcriptome assembly and isoform annotation by hybrid sequencing.</li> 
      </ul>
    </div>
    
    <div id="page_title_rightcontent">
	<ul>


	    <li>&nbsp;</li>

		<li><img src="images/IDP-fusion.png" width="300" >&nbsp;&nbsp;&nbsp;&nbsp;</li>
		
	</ul>
    </div>

<p class="page_title_area_lower">Latest News:  IDP-denovo_20160826 is released <a href="default.asp#news">read more</a></p>
    
    
  </div>
