  <div id="page_title_area">
    <!-- STANDARD PAGE TITLE; NO DECORATIVE GRAPHIC -->
    <!-- <div id="page_title_leftcontent"> -->
    <div id="page_title_leftcontent">
      <h1>GenoClone</h1>
      <ul>
        <li>GenoClone is a tool for <b>subclone inference <br></b>and studying <b>tumor heterogenity</b> 

      </ul>
    </div>
    
    <div id="page_title_rightcontent">
	<ul>


	    <li>&nbsp;</li>

		<li><img src="images/GenoClone.png" width="500" >&nbsp;&nbsp;&nbsp;&nbsp;</li>
		
	</ul>
    </div>

<p class="page_title_area_lower">Latest News:  GenoClone is released <a href="default.asp#news">read more</a></p>
    
    
  </div>