<div id="sidebar">
    <h2>Site Map</h2>
    <ul>
      <li><a href="default.asp">Home</a></li>
      
      <li><a href="IDP-fusion_download_current.asp">Downloads</a></li>
      <li><a href="IDP-fusion_contact.asp">Contact</a></li>
      <li><a href="IDP-fusion_requirements.asp">Requirements</a></li>
      <li><a href="IDP-fusion_howitworks.asp">How it works?</a></li>
<li><a href="IDP-fusion_long_read_file_guide.asp">Long read file guide</a></li>
<li><a href="IDP-fusion_cfg.asp">CFG file format</a></li>


  <li><a href="IDP-fusion_faq.asp">FAQ</a></li>

    </ul>
    <h3>Help</h3>
    <ul>
      
     

      <li><a href="IDP-fusion_manual.asp">Manual</a></li>
      <li><a href="IDP-fusion_tutorial.asp">Tutorial</a></li>
      
    </ul>
    <h2>Download</h2>
    <h3>Current release</h3>
    <ul>
      <li><a href="IDP-fusion_download_current.asp"><img src="images/download.png"> IDP-fusion 1.1.1 </a> (<a href="IDP-fusion_download_current.asp#notes">notes</a>)</li>
    </ul>

    <!-- #include file="usefullinks.inc" -->

    <br><ul><center><img src="images/seal.gif" width="75%" hight="75%"><center></ul>
  </div>





