<div id="sidebar">
    <h2>Site Map</h2>
    <ul>
      <li><a href="default.asp">Home</a></li>
      
      <li><a href="AlignQC_download_current.asp">Downloads</a></li>
      <li><a href="AlignQC_contact.asp">Contact</a></li>
      <li><a href="AlignQC_requirements.asp">Requirements</a></li>
      
  
    </ul>
    <h3>Help</h3>
    <ul>
      
     

      <li><a href="AlignQC_manual.asp">Manual</a></li>
      
      
    </ul>
    <h2>Download</h2>
    <h3>Current release</h3>
    <ul>
      <li><a href="AlignQC_download_current.asp"><img src="images/download.png"> AlignQC 1.2</a> (<a href="AlignQC_download_current.asp#notes">notes</a>)</li>
    </ul>

    <!-- #include file="usefullinks.inc" -->

    <br><ul><center><img src="images/seal.gif" width="75%" hight="75%"><center></ul>
  </div>
