  <div id="page_title_area">
    <!-- STANDARD PAGE TITLE; NO DECORATIVE GRAPHIC -->
    <!-- <div id="page_title_leftcontent"> -->
    <div id="page_title_leftcontent">
      <h1>AlignQC</h1>
      <ul>
        <li>AlignQC is a tool for <b>assessing an alignment, <br></b>and <b>generating reports</b> that are easy to share

      </ul>
    </div>
    
    <div id="page_title_rightcontent">
	<ul>


	    <li>&nbsp;</li>

		<li><img src="images/errorpattern.png" width="150" >&nbsp;&nbsp;&nbsp;&nbsp;</li>
		
	</ul>
    </div>

<p class="page_title_area_lower">Latest News:  AlignQC is released <a href="default.asp#news">read more</a></p>
    
    
  </div>