<div id="sidebar">
    <h2>Site Map</h2>
    <ul>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au">Home Page</a></li>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/publications">Publications</a></li>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/labmembers">Lab Members</a></li>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/utility_script.asp">Utilities</a></li>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/contact/">Contact</a></li>
    </ul>

    <h2>Software</h2>
    <ul>

    <li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP/">IDP</a> - Isoform Detection and Prediction
      <br><a href="http://www.healthcare.uiowa.edu/labs/au/IDP/IDP_download_current.asp"><img src="images/download.png">IDP 0.1.8</a> (<a href="http://www.healthcare.uiowa.edu/labs/au/IDP/IDP_download_current.asp#0.1">notes</a>)</li>

    <li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP-ASE/">IDP-ASE</a> - IDP for Allele-Specific Expression
      <br><a href="http://www.healthcare.uiowa.edu/labs/au/IDP-ASE/IDP-ASE_download_current.asp"><img src="images/download.png">IDP-ASE 20161017</a> (<a href="http://www.healthcare.uiowa.edu/labs/au/IDP-ASE/IDP-ASE_download_current.asp#0.1">notes</a>)</li>
          
    <li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP-fusion/">IDP-fusion</a> - Fusion Isoform Detection and Prediction
      <br><a href="http://www.healthcare.uiowa.edu/labs/au/IDP-fusion/"><img src="images/download.png">IDP-fusion </a> (<a href="http://www.healthcare.uiowa.edu/labs/au/IDP-fusion/IDP-fusion_download_current.asp#0.1">notes</a>)</li>
      
 
    <li><a href="http://www.healthcare.uiowa.edu/labs/au/LSC/">LSC</a> - Rapid error correction tool for PacBio data 
      <br><a href="http://www.healthcare.uiowa.edu/labs/au/LSC/LSC_download.asp"><img src="images/download.png">LSC 2.0</a> (<a href="http://www.healthcare.uiowa.edu/labs/au/LSC/LSC_download.asp#2.0">notes</a>)</li>
    
      <li><a href="http://www.stanford.edu/group/wonglab/SpliceMap/">SpliceMap</a> - De novo splice junction discovery and alignment tool 
    <br><a href="http://www.stanford.edu/group/wonglab/SpliceMap/download.html"><img src="images/download.png"> SpliceMap 3.3.5.2</a> (<a href="http://www.stanford.edu/group/wonglab/SpliceMap/download.html#3.3.5.2">notes</a>)</li>

      <li><a href="http://www.healthcare.uiowa.edu/labs/au/AlignQC/AlignQC_download_current.asp">AlignQC</a> - Alignment quality control reporting tool 
    <br><a href="http://www.healthcare.uiowa.edu/labs/au/AlignQC/AlignQC_download_current.asp"><img src="images/download.png"> AlignQC 1.2</a> (<a href="http://www.healthcare.uiowa.edu/labs/au/AlignQC/AlignQC_download_current.asp#notes">notes</a>)</li>
    

<li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP-denovo/IDP-denovo_download_current.asp">IDP-denovo</a> - <i>de novo</i> transcriptome assembly and annotation tool 
    <br><a href="http://www.healthcare.uiowa.edu/labs/au/IDP-denovo/IDP-denovo_download_current.asp"><img src="images/download.png"> IDP-denovo 0.2</a> (<a href="http://www.healthcare.uiowa.edu/labs/au/IDP-denovo/IDP-denovo_download_current.asp#notes">notes</a>)</li>


<li><a href="http://www.healthcare.uiowa.edu/labs/au/GenoClone/">GenoClone</a> - Reveal tumor heterogeneity
    <br><a href="http://www.healthcare.uiowa.edu/labs/au/GenoClone/GenoClone_download_current.asp"><img src="images/download.png"> GenoCone 0.1</a> (<a href="http://www.healthcare.uiowa.edu/labs/au/GenoClone/GenoClone_download_current.asp#notes">notes</a>)</li>





    </ul>
  
    <!-- #include file="usefullinks.inc" -->

  <br><ul><center><img src="images/seal.gif" width="75%" hight="75%"><center></ul>
</div>