<div id="sidebar">
    <h2>Site Map</h2>
    <ul>
      <li><a href="default.asp">Home</a></li>
      <li><a href="LSC_howitworks.asp">How it works?</a></li>
      <li><a href="LSC_download.asp">Downloads</a></li>
      <li><a href="LSC_contact.asp">Contact</a></li>
      <li><a href="LSC_requirements.asp">Requirements</a></li>
      <li><a href="https://github.com/jason-weirather/LSC/">Code</></li>
  
    </ul>
    <h3>Help</h3>
    <ul>
      <li><a href="LSC_tutorial.asp">Tutorial</a></li>
      <li><a href="LSC_manual.asp">Manual</a></li>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/utility_script.asp">Utilities</a></li>
      <li><a href="LSC_faq.asp">FAQ</a></li>
    </ul>
    <h2>Download</h2>
    <h3>Current release</h3>
    <ul>
      <li><a href="LSC_download.asp"><img src="images/download.png"> LSC 2.0</a> (<a href="LSC_download.asp#2.0">notes</a>)</li>
    </ul>

    <!-- #include file="usefullinks.inc" -->

    <br><ul><center><img src="images/seal.gif" width="75%" hight="75%"><center></ul>
  </div>
