<div id="sidebar">
    <h2>Site Map</h2>
    <ul>
      <li><a href="default.asp">Home</a></li>
      <li><a href="IDP-ASE_guide.asp">Setup guide</a></li>
      <li><a href="IDP-ASE_download_current.asp">Downloads</a></li>
      <li><a href="IDP-ASE_contact.asp">Contact</a></li>
    </ul>
    <h2>Download</h2>
    <h3>Current release</h3>
    <ul>
      <li><a href="IDP-ASE_download_current.asp"><img src="images/download.png"> IDP-ASE_20160516</a> (<a href="IDP-ASE_download_current.asp#notes">notes</a>)</li>
    </ul>

    <h2>Useful links</h2>
    <ul>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/">Au Lab</a> - Au Lab homepage </li>
    </ul>
    <ul>
      <li><a href="http://www.stanford.edu/group/wonglab/SpliceMap/">SpliceMap</a> - Novel splice junction discovery</li>
    </ul>
    <ul>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/LSC/LSC.html">LSC</a> - Error correction of PacBio long reads </li>
    </ul>
    <ul>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP/">IDP</a> - Isoform Detection and Prediction  </li>
    </ul>
    <ul>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP-fusion/">IDP-fusion</a> - Isoform Detection and Prediction across fusion genes </li>
    </ul>
    <ul>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP/hESC.asp">hESC transcriptome</a> - hESC transcriptome by IDP </li>
    </ul>

    <br><ul><center><img src="images/seal.gif" width="75%" hight="75%"><center></ul>
  </div>
