  <div id="page_title_area">
    <!-- STANDARD PAGE TITLE; NO DECORATIVE GRAPHIC -->
    <!-- <div id="page_title_leftcontent"> -->
    <div id="page_title_leftcontent">
      <h1>IDP-ASE</h1>
      <ul>
        <li>IDP-ASE is a tool for <b>haplotyping and quantifying allele-specific expression</b> <br> from Second Generation Sequencing and PacBio sequencing. 
      </ul>
    </div>
    
    <div id="page_title_rightcontent">
	<ul>


	    <li>&nbsp;</li>

		<li><img src="images/IDP-fusion.png" width="300" >&nbsp;&nbsp;&nbsp;&nbsp;</li>
		
	</ul>
    </div>

<p class="page_title_area_lower">Latest News:  IDP-ASE_20160516 is released <a href="default.asp#news">read more</a></p>
    
    
  </div>
