<div id="sidebar">
    <h2>Site Map</h2>
    <ul>
      <li><a href="hESC.asp">Home</a></li>
      <li><a href="hESC_Gene_isoform_detection_and_prediction.asp">Gene isoform detection and prediction</a></li>
      <li><a href="hESC_hESC-specific_novel_genes.asp">hESC-specific novel genes</a></li>
      <li><a href="hESC_Novel_gene_isoforms.asp">Novel gene isoforms</a></li>
    <li><a href="hESC_Quantification_of_isoform_abundance.asp">Quantification of isoform abundance</a></li>
    <li><a href="hESC_Isoforms_of_pluripotent_stem_cell_markers.asp">Isoforms of pluripotent stem cell markers</a></li>
    <li><a href="hESC_ncRNA_identification.asp">ncRNA identification</a></li>
    <li><a href="hESC_Data.asp">Data</a></li>
    
    </ul>
    <h3>Help</h3>
    <ul>
    <li><a href="hESC_gpd_format.asp">GPD format</a></li>
      <li><a href="hESC_howitworks.asp">How it works?</a></li>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/IDP/hESC_long_read_file_guide.html">Generate long read files</a></li>
      <li><a href="http://www.healthcare.uiowa.edu/labs/au/utility_script.asp">Utilities</a></li>
      <li><a href="hESC_faq.asp">FAQ</a></li>
      <li><a href="hESC_contact.asp">Contact</a></li>
    </ul>

    <!-- #include file="usefullinks.inc" -->



    <br><ul><center><img src="images/seal.gif" width="75%" hight="75%"><center></ul>
  </div>