  <div id="page_title_area">
    <!-- STANDARD PAGE TITLE; NO DECORATIVE GRAPHIC -->
    <!-- <div id="page_title_leftcontent"> -->
    <div id="page_title_leftcontent">
      <h1>hESC transcriptome</h1>
      <ul>
        <li>This Human Embryonic Stem Cell <br>(hESC, H1 cell line) <br>transcriptome is identified by <a href="http://www.stanford.edu/group/wonglab/SpliceMap/"><b>SpliceMap</b></a>-<a href="http://www.healthcare.uiowa.edu/labs/au/LSC/"><b>LSC</b></a>-<a href="http://www.healthcare.uiowa.edu/labs/au/IDP/"><b>IDP</b></a> pipeline<br>

      </ul>
    </div>
    
    <div id="page_title_rightcontent">
  <ul>


      <li>&nbsp;</li>

    <li><img src="images/IDP.png" width="300" >&nbsp;&nbsp;&nbsp;&nbsp;</li>
    
  </ul>
    </div>
    
    
  </div>